### ISSUE TITLE
Player can still fire gun while in hands up mode

### ISSUE THREAD

**Issue by CheeseCake87** [KadDarem/Walkable-Hands-Up#1]
Would be a good to have the players gun disabled during handsup true. Easily abused in game due to the gun still able to fire.

**Comment by Thasimo1** [comment]
> Would be a good to have the players gun disabled during handsup true. Easily abused in game due to the gun still able to fire.

Have the same problem.. Can someone help?

**Comment by ghost** [comment]
I can help but do you both need help anymore? It's 2022.

**Comment by Thasimo1** [comment]
For me not anymote. But someone maybe would want to😅
